CALL fabricante ("Asus");
CALL fabricante ("Lenovo");
CALL fabricante ("Hewlett-Packard");
CALL fabricante ("Samsung");
CALL fabricante ("Seagate");
CALL fabricante ("Crucial");
CALL fabricante ("Gigabyte");
CALL fabricante ("Huawei");
CALL fabricante ("Xiaomi");
/*___________________________________________________________________________________________________________________________________________*/
CALL Productos ("Disco duro SATA3 1TB",86.99,5);
CALL Productos ("Memoria RAM DDR4 8GB", 120,6);
CALL Productos ("Disco SSD 1TB",150.99,4);
CALL Productos ("GeForce GTX 1050Ti",185,7);
CALL Productos ("GeForce GTX 1080 Xtreme",755,6);
CALL Productos ("Monitor 24 LED Full HD",202,1);
CALL Productos ("Monitor 27 LED Full HD",245.99,1);
CALL Productos ("Portatil Yoga 520",559,2);
CALL Productos ("Portatil Ideapd 320",444,2);
CALL Productos ("Impresora HP Deskjet 3720",59.99,3);
CALL Productos ("Impresora HP Laserjet Pro M26nw",180,3);